### ISSUE TITLE
Crashing on test data.

### ISSUE THREAD

**Issue by humberto-ortiz** [Kevinlega/DBGDE#3]
$ python ../dbgfix.py -A A.fq -B B.fq -o AB.dif -k 21
Traceback (most recent call last):
  File "../dbgfix.py", line 204, in <module>
    main()
  File "../dbgfix.py", line 187, in main
    write_GFA2(G,cs,args.k,d,file)
  File "../dbgfix.py", line 158, in write_GFA2
    get_kmers(x,d,k,i,fd)                     # Function to get the fragments of organism A and B if included
  File "../dbgfix.py", line 152, in get_kmers
    lastkmerid[s] = (('%s:%s:(A:%s,B:%s)')%(s,x,d[keyA][0],d[keyA][1]))
NameError: name 'keyA' is not defined

**Comment by Kevinlega** [comment]
Fixed on commit c250805
